const languagedata = {
    en: {
        welcome: "Welcome to the Dashboard",
        ntp: "NTP",
        irrigation: "Irrigation",
        price: "Price",
        settings: "Settings",
        storeWelcome: "Welcome to the store!",
        basicPlan: "BASIC PLAN",
        standardPlan: "STANDARD PLAN",
        premiumPlan: "PREMIUM PLAN",
        ultimatePlan: "ULTIMATE PLAN",
        basicDesc: "Access to weather updates and basic crop recommendations.",
        standardDesc: "Includes pest detection, soil health analysis, and detailed crop management tips.",
        premiumDesc: "Complete access to all features, including market trends and government scheme alerts.",
        ultimateDesc: "Full suite of services, personalized recommendations, and one-on-one expert consultations.",
        inCart: "In Cart",
        addToCart: "Add To Cart",
        removeFromCart: "Remove from cart",
        itemsInCart: "Items in your cart:",
        noItems: "There are no items in your cart!",
        total: "Total",
        purchase: "Purchase items!",
        cartTitle: "Shopping Cart",
        cartButton: "Cart",
        cancelMessage: "Sorry to see you cancelled your Stripe payment!",
        successMessage: "Thank you for your purchase!",
    },
    ka: {
        welcome: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಸುಸ್ವಾಗತ",
        ntp: "ಎನ್‌ಟಿಪಿ",
        irrigation: "ನೀರಾವರಿ",
        price: "ಬೆಲೆ",
        settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        storeWelcome: "ಅಂಗಡಿಗೆ ಸ್ವಾಗತ!",
        basicPlan: "ಮೂಲ ಯೋಜನೆ",
        standardPlan: "ಸ್ಟಾಂಡರ್ಡ್ ಯೋಜನೆ",
        premiumPlan: "ಪ್ರೀಮಿಯಂ ಯೋಜನೆ",
        ultimatePlan: "ಅಲ್ಟಿಮೇಟ್ ಯೋಜನೆ",
        basicDesc: "ಹವಾಮಾನ ಮಾಹಿತಿಗೆ ಪ್ರವೇಶ ಮತ್ತು ಮೂಲ ಬೆಳೆ ಶಿಫಾರಸುಗಳು.",
        standardDesc: "ಹೋಲುವುಗಳ ಪತ್ತೆ, ಮಣ್ಣು ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆ, ಮತ್ತು ವಿವರವಾದ ಬೆಳೆ ನಿರ್ವಹಣಾ ಟಿಪ್ಸ್ ಸೇರಿಸಲಾಗಿದೆ.",
        premiumDesc: "ಎಲ್ಲಾ ವೈಶಿಷ್ಟ್ಯಗಳಿಗೆ ಸಂಪೂರ್ಣ ಪ್ರವೇಶ, ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳು ಮತ್ತು ಸರ್ಕಾರದ ಯೋಜನೆಗಳ ಎಚ್ಚರಿಕೆಗಳು.",
        ultimateDesc: "ಸಂಪೂರ್ಣ ಸೇವೆಗಳ ಪ್ಯಾಕೇಜ್, ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳು, ಮತ್ತು ಒನ್-ಆನ್-ಒನ್ ತಜ್ಞರ ಸಲಹೆ.",
        inCart: "ಕಾರ್ಟ್‌ನಲ್ಲಿ",
        addToCart: "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
        removeFromCart: "ಕಾರ್ಟ್‌ನಿಂದ ತೆಗೆದುಹಾಕಿ",
        itemsInCart: "ನಿಮ್ಮ ಕಾರ್ಟ್‌ನಲ್ಲಿ ಇರುವ ವಸ್ತುಗಳು:",
        noItems: "ನಿಮ್ಮ ಕಾರ್ಟ್‌ನಲ್ಲಿ ಯಾವುದೇ ವಸ್ತುಗಳಿಲ್ಲ!",
        total: "ಒಟ್ಟು",
        purchase: "ವಸ್ತುಗಳನ್ನು ಖರೀದಿಸಿ!",
        cartTitle: "ಶಾಪಿಂಗ್ ಕಾರ್ಟ್",
        cartButton: "ಕಾರ್ಟ್",
        cancelMessage: "ನೀವು ನಿಮ್ಮ ಸ್ಟ್ರೈಪ್ ಪಾವತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿದುದು ವಿಷಾದಕರವಾಗಿದೆ!",
        successMessage: "ನಿಮ್ಮ ಖರೀದಿಗೆ ಧನ್ಯವಾದಗಳು!",
    },
  };
  

  export default languagedata;
  